---
- name: stoping apache2
  hosts: all
  become: true
  tasks:

    - name: removing git
      apt:
        name: git*
        state: absent

    - name: stoping apache2 service
      service:
        name: apache2
        state: stopped

    - name: unistalling apche2
      apt:
        name: apache2*
        state: absent
